### ISSUE TITLE
critic model is not using lstm 

### ISSUE THREAD

**Issue by verystrongjoe** [fshamshirdar/pytorch-rdpg#3]
I have a question. In the paper, critic model also use recurrent network. but in your code is not using lstm but use just 3 dense layers like normal critic model. right? I just checked your code. Because I don't know how to forward time sequence data to critic out of actor lstm policy.

**Comment by fshamshirdar** [comment]
Oops, yes you're right. I should have added the lstm cell to that too. you could also merge ActorCritic models to have one model with action/value outputs.
